* API Design

** Group

*** List All Posts by Date
按照天，星期，月份返回帖子总数以及帖子的 id

#+BEGIN_SRC python
GET /groups/{group_id}/posts
#+END_SRC

**** Parameters
| Name     | Type   | Description                                     |
|----------+--------+-------------------------------------------------|
| group_id | String | group id                                        |
| range    | String | 可选。默认为 day，可选的参数有 day，week，month |
|----------+--------+-------------------------------------------------|

**** Response
#+BEGIN_SRC json
Status: 200 OK
-------
[
    "group_name": "hello",
    "group_id": "xxxxxx",
    "published_at": "2015-08-05T08:40:51.620Z",
    "post_num": 123,
    "posts": [
        {
            "post_id": "1241414",
            "user_id": "xxxxx"
        },
        {
            "post_id": "1231414",
            "user_id": "xxxxx"
        }
    ]
]
#+END_SRC

** Users

*** 获得用户数

根据日期和是否拥有设备，返回用户总数
#+BEGIN_SRC python
GET /users/count
#+END_SRC

**** Parameters
| Name        | Type   | Description                                                         |
|-------------+--------+---------------------------------------------------------------------|
| datetime    | String | 可选。默认为当前日期。查询该日期前的所有用户数                      |
| has_devices | bool   | 可选。默认 False，返回所有用户。如果为 True，返回拥有设备的所有用户 |
| has_orders  | bool   | 可选。默认 False，返回所有用户。True，返回拥有订单的用户数           |
|-------------+--------+---------------------------------------------------------------------|

**** Response
#+BEGIN_SRC json
Status: 200 OK
-----
{
    "datetime": "2015-08-05T08:40:51.620Z",
    "users_count": 123111441
}
#+END_SRC


** Orders

*** 订单查询
按照已成交、已确认、无效或已取消、未确认对订单进行查询

#+BEGIN_SRC python
GET /orders
#+END_SRC

**** Parameters
| Name          | Type   | Description                                                                        |
|---------------+--------+------------------------------------------------------------------------------------|
| status        | String | 可选。默认为 all，返回所有订单。 可选参数为 all,deal, confirmed, invalid,cancelled |
| delivery_type | String | 可选。默认返回所有配送方式的订单。可选参数为 a,b,c                                 |
| payment_type  | String | 可选。默认返回所有支付方式的订单。可选参数为 alipay, wechat                        |
|---------------+--------+------------------------------------------------------------------------------------|

**** Response
#+BEGIN_SRC json
Status: 200 OK
-----
{
    "orders_count": 1231,
    "orders_list" : [
        {
            "order_id": "12314141",
            "user_id": "",
            "datetime": "",
            "order_status": "comfirmed",
            "delivery_type": "",
            "payment_type": "alipay"
        },
        {
            "order_id": "444444",
            "user_id": "",
            "datetime": "",
            "order_status": "cancelled",
            "delivery_type": "",
            "payment_type": "alipay"
        }
    ]
}
#+END_SRC

*** 关键词统计
    返回关键词统计结果。
    按照日、周、年返回高频查询数据。

    #+BEGIN_SRC python
    GET /keywords/
    #+END_SRC

**** Parameters
| Name      | Type   | Description                                      |
|-----------+--------+--------------------------------------------------|
| range     | String | 可选。默认为 day，可选的参数有 day，week，month  |
| sort_type | String | 可选。默认为降序排列。可选类型为 descend, ascend |
| limit     | int    | 可选。默认返回前 100 条数据。                    |
|-----------+--------+--------------------------------------------------|

**** Response

#+BEGIN_SRC json
Status: 200 OK
-----
{
    "keywords_count": 100,
    "sort_type": "descend",
    "limit": 100,
    "range": "day",
    "keywords_list" : [
        {
            "keyword": "健身",
            "frequency": 20
        },
        {
            "keyword": "电子秤",
            "frequency": 10
        },
        ....
    ]
}
#+END_SRC
