* API Design

** Group

*** List All Posts by Date
按照天，星期，月份返回帖子总数以及帖子的 id

#+BEGIN_SRC python
GET /groups/{group_id}/posts
#+END_SRC

**** Parameters
| Name     | Type   | Description                                     |
|----------+--------+-------------------------------------------------|
| group_id | String | group id                                        |
| range    | String | 可选。默认为 day，可选的参数有 day，week，month |
|----------+--------+-------------------------------------------------|

**** Response
#+BEGIN_SRC json
Status: 200 OK
-------
[
    "group_name": "hello",
    "group_id": "xxxxxx",
    "published_at": "2015-08-05T08:40:51.620Z",
    "post_num": 123,
    "posts": [
        {
            "post_id": "1241414",
            "user_id": "xxxxx"
        },
        {
            "post_id": "1231414",
            "user_id": "xxxxx"
        }
    ]
]
#+END_SRC

*** 对每日、每周、每月各圈子发帖量进行排序
#+BEGIN_SRC python
GET /groups/posts
#+END_SRC

**** Parameters
| Name      | Type   | Description                                      |
|-----------+--------+--------------------------------------------------|
| range     | String | 可选。默认为 day，可选的参数有 day，week，month  |
|-----------+--------+--------------------------------------------------|

**** Response
#+BEGIN_SRC json
Status: 200 OK
-----
{
    "groups_count": 111,
    "groups_list": [
        {
            "group_id": "1111",
            "group_name": "",
            "posts_count": 111,
        },
        {
            "group_id": "2222",
            "group_name": "",
            "posts_count": 100,
        },
        ...
    ],

}
#+END_SRC


** Users

*** 获得用户数

根据日期和是否拥有设备，返回用户总数
#+BEGIN_SRC python
GET /users/count
#+END_SRC

**** Parameters
| Name        | Type   | Description                                                         |
|-------------+--------+---------------------------------------------------------------------|
| datetime    | String | 可选。默认为当前日期。查询该日期前的所有用户数                      |
| has_devices | bool   | 可选。默认 False，返回所有用户。如果为 True，返回拥有设备的所有用户 |
| has_orders  | bool   | 可选。默认 False，返回所有用户。True，返回拥有订单的用户数           |
|-------------+--------+---------------------------------------------------------------------|

**** Response
#+BEGIN_SRC json
Status: 200 OK
-----
{
    "datetime": "2015-08-05T08:40:51.620Z",
    "users_count": 123111441
}
#+END_SRC


** Orders

*** 订单查询
按照已成交、已确认、无效或已取消、未确认对订单进行查询

#+BEGIN_SRC python
GET /orders
#+END_SRC

**** Parameters
| Name          | Type   | Description                                                                        |
|---------------+--------+------------------------------------------------------------------------------------|
| status        | String | 可选。默认为 all，返回所有订单。 可选参数为 all,deal, confirmed, invalid,cancelled |
| delivery_type | String | 可选。默认返回所有配送方式的订单。可选参数为 a,b,c                                 |
| payment_type  | String | 可选。默认返回所有支付方式的订单。可选参数为 alipay, wechat                        |
|---------------+--------+------------------------------------------------------------------------------------|

**** Response
#+BEGIN_SRC json
Status: 200 OK
-----
{
    "orders_count": 1231,
    "orders_list" : [
        {
            "order_id": "12314141",
            "user_id": "",
            "datetime": "",
            "order_status": "comfirmed",
            "delivery_type": "",
            "payment_type": "alipay"
        },
        {
            "order_id": "444444",
            "user_id": "",
            "datetime": "",
            "order_status": "cancelled",
            "delivery_type": "",
            "payment_type": "alipay"
        }
    ]
}
#+END_SRC

** 关键词统计
    返回关键词统计结果。
    按照日、周、年返回高频查询数据。

    #+BEGIN_SRC python
    GET /keywords/{type}
    #+END_SRC

**** Parameters
| Name      | Type   | Description                                      |
|-----------+--------+--------------------------------------------------|
| type      | String | 必选。可选值为 store,group                        |
| range     | String | 可选。默认为 day，可选的参数有 day，week，month  |
| sort_type | String | 可选。默认为降序排列。可选类型为 descend, ascend |
| limit     | int    | 可选。默认返回前 100 条数据。                    |
|-----------+--------+--------------------------------------------------|

**** Response

#+BEGIN_SRC json
Status: 200 OK
-----
{
    "keywords_count": 100,
    "sort_type": "descend",
    "limit": 100,
    "range": "day",
    "keywords_list" : [
        {
            "keyword": "健身",
            "frequency": 20,
            "type": "group",
        },
        {
            "keyword": "电子秤",
            "frequency": 10,
            "type": "store"
        },
        ....
    ]
}
#+END_SRC


** 商品统计
*** 统计每个商品的销售量、访问量，以及进行排序。

    #+BEGIN_SRC python
    GET /goods/
    #+END_SRC

**** Parameters
| Name      | Type | Description                                   |
|-----------+------+-----------------------------------------------|
| sales     | bool | 默认返回所有商品，true 返回所有商品销售量     |
| visited   | bool | 默认返回所有商品，true 返回所有访问量         |
| is_sorted | bool | 默认 false，返回无序的。true 返回降序排序结果 |
|-----------+------+-----------------------------------------------|

**** Response

#+BEGIN_SRC json
Status: 200 OK
-----
{
    "goods_count": 1231,
    "goods_list" : [
        {
            "good_id": "12314124",
            "sales": 20,
            "visited": 100,
        },
        {
            "good_id": "3124141",
            "sales": 12,
            "visited": 13,
        },
        ....
    ]
}
#+END_SRC

** 数据比率统计

#+BEGIN_SRC python
GET /statistics/ratio
#+END_SRC

**** Response

#+BEGIN_SRC json
Status: 200 OK
-----
{
    "download_register_ratio": 0.69,
    "orders_ratio": {
        "deal_done": 0.4,
        "comfirmed": 0.2,
        "invalid": 0.1,
        "cancelled": 0.1,
        "uncomfirmed": 0.2
    },
    "payment": {
        "alipay": 0.66,
        "wechat": 0.34
    },
    "users": {
        "has_ordered": 0.51,
        "device_coverage": 0.22
    },
    "goods": {
        "visit_buy_ratio": 0.21
    }
}
#+END_SRC
